### ISSUE TITLE
Missing default_plugins.txt

### ISSUE THREAD

**Issue by Xeddius** [incognico/svencoop_plugins#1]
I'm looking to build a listenserver for a Lan game. (My internet is extremely slow here) I just want to enjoy Sven maps offline and with a friend on my lan. However I would like to have some of the features that are found in many dedicated servers. As you can imagine, people are hesitant to give a stranger any of their server files, given the risk that they might try to clone or copy a server. If you aren't willing to share a default_plugins, please consider helping me to at least set up a buymenu or something simple to improve the experience on my lan games. (I already have MetaMod and AMX working on a listen server with a custom SCXPM plugin.)

**Comment by incognico** [comment]
The default plugins file is pretty self explainable. If you need general help come to the SC discord: https://discord.gg/0wtJ6aAd7XOGI6vI or ask at the SC forums.
