### ISSUE TITLE
Custom Votes

### ISSUE THREAD

**Issue by s00172994** [incognico/svencoop_plugins#2]
I am trying to use your custom votes snippet but I run into console errors shown below at these two lines of code.

`ABCVote.SetVoteBlockedCallback( @ABCVoteBlocked );`
`ABCVote.SetVoteEndCallback( @ABCVoteEnd );`

![image](https://user-images.githubusercontent.com/25370364/41494028-e343bda6-7105-11e8-8858-8926b6a3fe6d.png)

I'm unsure as to what the method arguments being passed into SetVoteBlockedCallback and SetVoteEndCallback do exactly.

**Comment by incognico** [comment]
it's just the function name of what will be called, looks like you set the callback to @bla but don't have a function bla()
