### ISSUE TITLE
Menu sometimes can be override by another plugin that has menu

### ISSUE THREAD

**Issue by Tucumanos** [incognico/svencoop_plugins#3]
Sometimes players can't vote because the menu dissapears if they use another plugin with menu or players that connect during the vote, I think that an solution could be if the menu is sended constantly. I ask you to fix this because MrOats doesn't longer support his plugins. Thanks.

**Comment by incognico** [comment]
Yes its a crap plugin but it does the job. I won't touch if someone sends a pull request with a fix I'll merge it.
