### ISSUE TITLE
Playerprecachedyn Symlink how to Symlink for win7?

### ISSUE THREAD

**Issue by longlong2002** [incognico/svencoop_plugins#8]

**Comment by incognico** [comment]
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc753194(v=ws.10)?redirectedfrom=MSDN
probably `mklink /d ...` or something, see https://superuser.com/questions/752538/mklink-vs-junction-exe

**Comment by longlong2002** [comment]
also need link folder and file
